<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-01-26 13:27:51
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [
            '/js/all-f6792293332abe6477bbb1f30a53bfc5.js',
        ],
        'css' => [
            '/css/all-bca7195c46a35297d42d0b225d8d5f28.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'frontend\\assets\\CdnAsset' => [
        'css' => [
            'https://fonts.googleapis.com/css?family=Roboto:400,500,700',
        ],
        'js' => [
            'https://code.jquery.com/jquery-migrate-1.3.0.min.js',
            'https://code.jquery.com/ui/1.11.4/jquery-ui.min.js',
            '//www.googleadservices.com/pagead/conversion.js',
        ],
        'jsOptions' => [
            'position' => 3,
        ],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\CdnAsset',
    ],
    'yii\\widgets\\MaskedInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'all',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'all',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'all',
        ],
    ],
    'artweb\\artbox\\assets\\LazyLoadAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'artweb\\artbox\\assets\\LazyAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'artweb\\artbox\\assets\\LazyLoadAsset',
            'all',
        ],
    ],
    'frontend\\assets\\FancyboxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\CdnAsset',
            'yii\\widgets\\MaskedInputAsset',
            'yii\\widgets\\ActiveFormAsset',
            'yii\\validators\\ValidationAsset',
            'artweb\\artbox\\assets\\LazyAsset',
            'frontend\\assets\\FancyboxAsset',
            'all',
        ],
    ],
];